#file: noinspection HttpUrlsUsage

spring:
  #enable .env.properties file
  config:
    import: optional:classpath:.env.properties

--- # DB
spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:testdb}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:sa}
    driverClassName: ${DB_DRIVER_CLASS_NAME:org.h2.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: ${DB_HIBERNATE_DIALECT:org.hibernate.dialect.H2Dialect}
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true

--- # Eureka client
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka

--- # Keycloak
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_SERVER_HOST:localhost}:8080/realms/DevVault-v2.0

--- # Swagger
springdoc:
  swagger-ui:
    oauth:
      client-id: ${KEYCLOAK_CLIENT_ID}
      client-secret: ${KEYCLOAK_CLIENT_SECRET}

--- # Custom variables
endpoint:
  base-url: /api/v1